/* Rules:

   1. Don't include "www" / "ww" prefix
   2. Don't sort the list. Maintainer will do it.
 */

var sites = [
    "7jiu.com.hk",
    "a-gui.com",
    "apple01.net",
    "asia01.club",
    "axn2000.blogspot.*",
    "bomb01.com",
    "bubuko.com",
    "bunnygo.net",
    "buzz01.com",
    "buzzhand.com",
    "buzzhand.net",
    "buzzlife.com.tw",
    "buzznews.news",
    "ccolorsky.blogspot.com",
    "circle01.com",
    "ck101.com",
    "clickme.net",
    "cmoney.tw",
    "contw.com",
    "daleba.net",
    "daliulian.net",
    "discoss.com",
    "dnbcw.info",
    "dsy39.com",
    "eazon.com",
    "enews.com.tw",
    "ezgoe.com",
    "ezvivi2.com",
    "faminereports.blogspot.*",
    "fanli7.net",
    "funnies.online",
    "funvdo01.com",
    "getfunfun.com",
    "getjoyz.com",
    "gigacircle.com",
    "gjoyz.com",
    "guudo.cn",
    "happies.news",
    "happyeverydaymovie.com",
    "hk.maheshbhusal.com.np",
    "hkwall.com",
    "hothk.com",
    "how01.com",
    "howfunny.org",
    "hssszn.com",
    "icovideos.com",
    "ideapit.com",
    "ilife97.com",
    "immediates.net",
    "juksy.com",
    "kan.world",
    "kuso01.tv",
    "laughbombclub.com",
    "letu.life",
    "life.com.tw",
    "life.cx", // This domain will redirect to life.tw
    "life.tw",
    "likea.ezvivi.com",
    "mama.tw",
    "mamicode.com",
    "mango01.com",
    "medialnk.com",
    "metalballs.com",
    "mili010.com",
    "mili010.net",
    "ml.design-fabrica.com", // Whole HK
    "myfbshare.net",
    "newstube01.tv",
    "novelfeed.com",
    "onefunnyjoke.com",
    "orange01.org",
    "peopleinsider.blogspot.*",
    "peopleinsider.net",
    "picallies.com",
    "programgo.com",
    "ptt01.cc",
    "pttbook.com",
    "push01.com",
    "push01.net",
    "qianqu.cc",
    "qilook.com",
    "qiqu.news",
    "reg.youthwant.com.tw",
    "share.youthwant.com.tw",
    "share001.com",
    "share001.net",
    "share2fb.net",
    "shareba.com",
    "shareonion.com",
    "spicemami.com",
    "superfun-e.com",
    "teepr.com",
    "thefundaily.com",
    "ttshow.tw",
    "tw.anyelse.com",
    "tw.jdkartsports.nl/", // Whole HK
    "vdoobv.com",
    "viralane.com",
    "watchinese.com",
    "wholehk.com",
    "wonder4.co",
    "yourfacts.club", // FB Share trap
    "yourhope.info",
    "youthwant.com",
    "youthwant.com.tw",
    "youthwant.ufc.com.tw",
    "youthwant.xnnow.com",
    "hehuancui.com", // buzz01
    "video-lab.net" //Whole HK
];

module.exports = sites;
