/* Rules:

   1. Don't include "www" prefix
 */

var sites = [
    "life.com.tw",
    "yourhope.info",
    "mama.tw",
    "teepr.com",
    "onefunnyjoke.com",
    "buzzhand.com",
    "buzzhand.net",
    "ptt01.cc",
    "gigacircle.com",
    "eazon.com",
    "juksy.com",
    "peopleinsider.net",
    "peopleinsider.blogspot.*",
    "viralane.com",
    "metalballs.com",
    "funvdo01.com",
    "likea.ezvivi.com",
    "youthwant.com.tw",
    "youthwant.com",
    "share.youthwant.com.tw",
    "reg.youthwant.com.tw",
    "youthwant.ufc.com.tw",
    "youthwant.xnnow.com",
    "pttbook.com",
    "newstube01.tv",
    "bomb01.com",
    "share001.net",
    "cmoney.tw",
    "daliulian.net",
    "hssszn.com",
    "hothk.com",
    "kuso01.tv",
    "shareba.com",
    "discoss.com",
    "faminereports.blogspot.*",
    "dsy39.com",
    "wholehk.com",
    "push01.com",
    "how01.com",
    "getjoyz.com",
    "ezgoe.com",
    "ilife97.com",
    "buzzlife.com.tw",
    "superfun-e.com",
    "ck101.com",
    "spicemami.com",
    "picallies.com",
    "guudo.cn",
    "fanli7.net",
    "bubuko.com",
    "mamicode.com",
    "programgo.com",
    "dnbcw.info",
    "7jiu.com.hk",
    "yourfacts.club", // FB Share trap
    "tw.anyelse.com",
    "shareonion.com",
    "hkwall.com",
    "gjoyz.com",
    "buzz01.com",
    "orange01.org",
    "circle01.com",
    "qianqu.cc",
    "mango01.com",
    "clickme.net",
    "ezvivi2.com",
    "funnies.online",
    "laughbombclub.com",
    "thefundaily.com",
    "getfunfun.com",
    "myfbshare.net",
    "push01.net",
    "letu.life",
    "novelfeed.com",
    "www.enews.com.tw",
];

module.exports = sites;
